export default {
    GET_RESTUARANTS_LOADING: "GET_RESTUARANTS_LOADING",
    GET_RESTUARANTS_SUCCESS: "GET_RESTUARANTS_SUCCESS",
    GET_RESTUARANTS_FAILURE: "GET_RESTUARANTS_FAILURE",
    GET_RESTUARANT_LOADING: "GET_RESTUARANTS_LOADING",
    GET_RESTUARANT_SUCCESS: "GET_RESTUARANT_SUCCESS",
    GET_RESTUARANT_FAILURE: "GET_RESTUARANT_FAILURE"
}